18-349 Kernel: kernel.c File Reference
kernel.c File Reference
entry point to the raspberry pi kernel
#include <kstdint.h>
#include <timer.h>
#include <printk.h>
#include <arm.h>
#include <uart.h>
#include <supervisor.h>
#include <BCM2836.h>
#include <swi_num.h>
#include <syscalls.h>
Macros
#define IRQ_BASIC_PENDING (volatile uint32_t *) (MMIO_BASE_PHYSICAL + 0xB200)
IRQ basic pending register physcial address.
#define ENABLE_BASIC_IRQS (volatile uint32_t *) (MMIO_BASE_PHYSICAL + 0xB218)
enable basic IRQs register physical address
#define DISABLE_BASIC_IRQS (volatile uint32_t *) (MMIO_BASE_PHYSICAL + 0xB224)
disable basic IRQs register physical address
Functions
void kernel_main (void)
The kernel entry point.
void irq_c_handler (void)
Handler called when an IRQ occurs.
void * swi_c_handler (int swi_num, int *args)
Handles the given swi_num.
Detailed Description
entry point to the raspberry pi kernel
Date
10/12/17
Author
David Yu david.nosp@m.yu@a.nosp@m.ndrew.nosp@m..cmu.nosp@m..edu
Function Documentation
void* swi_c_handler (int swi_num, int * args)
Handles the given swi_num.
Parameters
swi_num the swi number passed in from swi_asm_handler
args pointer to arguments array, set up by the swi_asm_handler
Returns
the return result of the syscall
References SWI_CLOSE, SWI_EXIT, SWI_FSTAT, SWI_ISATTY, SWI_LSEEK, SWI_READ, SWI_SBRK, SWI_WRITE, syscall_close(), syscall_exit(), syscall_fstat(), syscall_isatty(), syscall_lseek(), syscall_read(), syscall_sbrk(), and syscall_write().